angular.module('galleryApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('app/views/extension.html',
    "<div id=extensions><div data-ng-model=package data-ng-show=package><h1 class=page-header>{{package.Name}}</h1><article class=extension><img class=preview data-ng-src={{package.Preview}} alt=\"{{package.Name}}\"><div class=properties><div class=details><p>{{package.Description}}</p><p><strong>Author:</strong> <a data-ng-href=\"/author/{{package.Author | lowercase | escape }}\">{{package.Author}}</a></p><p><strong>Supports:</strong> <span data-ng-repeat=\"version in package.SupportedVersions\">{{version + '&nbsp;'}}</span></p><p data-ng-show=package.Tags><strong>Tags:</strong> {{package.Tags}}</p><p><strong>Version:</strong> {{package.Version}}</p><p><strong>Updated:</strong> <time datetime=\"{{package.DatePublished | date:'yyyy-MM-dd'}}\">{{package.DatePublished | date:'MMM d. yyyy'}}</time></p></div><ul><li data-ng-show=package.MoreInfoUrl><a href={{package.MoreInfoUrl}}><span class=\"glyphicon glyphicon-home\" aria-hidden=true></span> Website</a></li><li data-ng-show=package.Repo><a href={{package.Repo}}><span class=\"glyphicon glyphicon-pencil\" aria-hidden=true></span> Source code</a></li><li data-ng-show=package.IssueTracker><a href={{package.IssueTracker}}><span class=\"glyphicon glyphicon-ok\" aria-hidden=true></span> Issue Tracker</a></li></ul><br><a class=\"btn btn-success\" href={{package.DownloadUrl}} target=_self><span class=\"glyphicon glyphicon-cloud-download\" aria-hidden=true></span> Download</a> <a class=\"btn btn-default\" href=/feed/extension/{{package.ID}} target=_self><span class=\"glyphicon glyphicon-cog\" aria-hidden=true></span> Feed</a></div></article><br><div data-ng-show=package.License class=clearfix><h2>License</h2><pre>{{package.License}}</pre></div></div></div>"
  );


  $templateCache.put('app/views/home.html',
    "<h1 class=page-header>{{pageTitle}} <a data-ng-href={{feed}} class=\"btn btn-default\"><span class=\"glyphicon glyphicon-cog\" aria-hidden=true></span> Feed</a></h1><div id=extensions><div id=searchform class=form-group><label class=sr-only for=search>Search</label><div class=input-group><div class=input-group-addon><span class=\"glyphicon glyphicon-search\"></span></div><input type=text id=search data-ng-model=query placeholder=Search class=\"form-control\"></div></div><article data-ng-repeat=\"package in packages | filter: packageSearch\"><a class=icon href=/extension/{{package.ID}}><img width=90 data-ng-src={{package.Icon}} alt=\"{{package.Name}}\"></a><div><h3><a data-ng-href=/extension/{{package.ID}}>{{package.Name}}</a> <span>v{{package.Version}}</span></h3><a data-ng-href=\"/author/{{package.Author | lowercase | escape }}\">{{package.Author}}</a><p>{{package.Description}}</p><a class=\"btn-sm btn-success\" href={{package.DownloadUrl}} target=_self><span class=\"glyphicon glyphicon-cloud-download\" aria-hidden=true></span> Download</a> <a class=\"btn-sm btn-default\" href=/feed/extension/{{package.ID}} target=_self><span class=\"glyphicon glyphicon-cog\" aria-hidden=true></span> Feed</a> <time datetime=\"{{package.DatePublished | date:'yyyy-MM-dd'}}\">{{package.DatePublished | date:'&nbsp;MMM d. yyyy'}}</time></div></article></div>"
  );


  $templateCache.put('app/views/upload.html',
    "<h1 class=page-header>Upload new extension</h1><p>Upload a new extension to the gallery. It can either be a brand new extension or and updated version of an extension that's already on the gallery.</p><form id=upload data-ng-hide=form.$submitted data-ng-submit=upload()><div class=form-group><label for=repo>Source code</label><input type=url data-ng-model=repo id=repo class=form-control placeholder=\"Url to the source code repository\"></div><div class=form-group><label for=issuetracker>Issue tracker</label><input type=url id=issuetracker data-ng-model=issuetracker class=form-control placeholder=\"Url to the issue tracker\"></div><div class=form-group><label for=uploadfile>Select file</label><input type=file id=uploadfile accept=.vsix required><p class=help-block>Only .vsix files are supported</p></div><input type=submit value=Upload class=\"btn-sm btn-primary\"><p class=has-error data-ng-show=\"upload.url.$invalid || error\">{{error}}</p></form>"
  );

}]);
